# Generated by Django 3.1.5 on 2021-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=16)),
                ('cvv', models.IntegerField(max_length=4)),
            ],
        ),
    ]
