# Generated by Django 3.1.5 on 2021-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCardChallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.IntegerField(),
        ),
    ]
