# Generated by Django 3.1.5 on 2021-02-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditCardChallenge', '0004_auto_20210131_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCard',
            new_name='CreditCardModel',
        ),
    ]
